[pytest]
addopts = -ra
testpaths = tests
filterwarnings =
    once::Warning
    ignore:::pympler[.*]


[gh-actions]
python =
    3.8: py38, typing
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    pypy3.8: pypy3
    pypy3.9: pypy3


[tox]
envlist =
    typing
    py{38,39,310,311,312,py3}-{crypto,nocrypto}
    pypi-description
isolated_build = True


[testenv]
# Prevent random setuptools/pip breakages like
# https://github.com/pypa/setuptools/issues/1042 from breaking our builds.
setenv =
    VIRTUALENV_NO_DOWNLOAD=1
extras =
    tests
    crypto: crypto
commands = {envpython} -b -m pytest {posargs}


[testenv:pypi-description]
basepython = python3.8
skip_install = true
deps =
    twine
    pip >= 18.0.0
commands =
    pip wheel -w {envtmpdir}/build --no-deps .
    twine check {envtmpdir}/build/*
